[versions]
agpVer = "8.13.0-alpha01"
firebaseBom = "34.0.0"
kotlinVer = "2.2.0"
composeVer = "1.8.3"
#composeMaterial3Ver = "1.3.1"
androidxActivityComposeVer = "1.10.1"
kotlinComposeVer = "1.8.2"
#material3AdaptiveVer = "1.0.0"
#material3AdaptiveNavigationSuiteVer = "1.3.1"
#androidxNavigationComposeVer = "2.8.4"
#navigationRuntimeKtxVer = "2.8.4"
#composeAnimationVer = "1.7.5"
#androidCoreVer = "1.15.0"
#lifecycleRuntimeKtxVer = "2.8.7"
jbNavigationComposeVer = "2.8.0-alpha13"
kamlVer = "0.85.0"
kotlinSerialJsonVer = "1.9.0"
#kotlinSerialYamlVer = "1.5.1"
okioVer = "3.15.0"
kotlinStdLibVer = "2.2.0"
androidxDatastoreVer = "1.1.7"
markdownVer="0.35.0"
purchases-kmp = "2.0.0+15.0.0"
google-services = "4.4.3"
settingsVer = "1.4.0-SNAPSHOT"
kcronVer = "0.23.0"

[libraries]
firebase-analytics = { module = "com.google.firebase:firebase-analytics" }
firebase-bom = { module = "com.google.firebase:firebase-bom", version.ref = "firebaseBom" }
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlinVer" }
kotlin-stdlib = { module = "org.jetbrains.kotlin:kotlin-stdlib", version.ref = "kotlinStdLibVer" }
jb-androidx-navigation-compose = { module = "org.jetbrains.androidx.navigation:navigation-compose", version.ref = "jbNavigationComposeVer" }

kcron-common = { module = "com.ucasoft.kcron:kcron-common", version.ref = "kcronVer" }

#androidx-core-ktx = { module = "androidx.core:core-ktx", version.ref = "androidCoreVer" }
#androidx-navigation-compose = { module = "androidx.navigation:navigation-compose", version.ref = "androidxNavigationComposeVer" }
#androidx-navigation-runtime-ktx = { group = "androidx.navigation", name = "navigation-runtime-ktx", version.ref = "navigationRuntimeKtxVer" }
#androidx-lifecycle-runtime-ktx = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtxVer"}
#
#androidx-compose-material3 = { module = "androidx.compose.material3:material3", version.ref = "composeMaterial3Ver" }
#androidx-compose-material3-adaptive-navigation = { module = "androidx.compose.material3.adaptive:adaptive-navigation", version.ref = "material3AdaptiveVer" }
#androidx-compose-material3-adaptive-navigation-suite = { module = "androidx.compose.material3:material3-adaptive-navigation-suite", version.ref = "material3AdaptiveNavigationSuiteVer" }

androidx-compose-material = { group = "androidx.compose.material", name = "material", version.ref = "composeVer" }
#androidx-compose-material-icons = { group = "androidx.compose.material", name = "material-icons-core", version.ref = "composeVer" }
#androidx-compose-material-ripple = { group = "androidx.compose.material", name = "material-ripple", version.ref = "composeVer" }
androidx-compose-runtime = { group = "androidx.compose.runtime", name = "runtime", version.ref = "composeVer" }
#androidx-compose-graphics = { group = "androidx.compose.ui", name = "ui-graphics", version.ref = "composeVer" }
#androidx-compose-animation = { module = "androidx.compose.animation:animation", version.ref = "composeAnimationVer" }

androidx-compose-ui = { module = "androidx.compose.ui:ui", version.ref = "composeVer" }
#androidx-compose-ui-util = { group = "androidx.compose.ui", name = "ui-util", version.ref = "composeVer" }
#androidx-compose-ui-text = { group = "androidx.compose.ui", name = "ui-text", version.ref = "composeVer" }
androidx-compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling", version.ref = "composeVer" }
androidx-compose-ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview", version.ref = "composeVer" }
androidx-compose-foundation = { module = "androidx.compose.foundation:foundation", version.ref = "composeVer" }
androidx-compose-activity = { module = "androidx.activity:activity-compose", version.ref = "androidxActivityComposeVer" }

androidx-datastore-core = { module = "androidx.datastore:datastore-core", version.ref = "androidxDatastoreVer" }
androidx-datastore-pref = { module = "androidx.datastore:datastore-preferences-core", version.ref = "androidxDatastoreVer" }

kaml = { module = "com.charleskorn.kaml:kaml", version.ref = "kamlVer" }
kotlin-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinSerialJsonVer" }
#kotlin-serialization-yaml = {group = "org.jetbrains.kotlinx", name="kotlinx-serialization-yaml", version.ref="kotlinSerialYamlVer" }

squareup-okio = { module = "com.squareup.okio:okio", version.ref = "okioVer" }

markdown-renderer = { module = "com.mikepenz:multiplatform-markdown-renderer", version.ref = "markdownVer"}
markdown-renderer-m2 = { module = "com.mikepenz:multiplatform-markdown-renderer-m2", version.ref = "markdownVer"}
markdown-renderer-m3 = { module = "com.mikepenz:multiplatform-markdown-renderer-m3", version.ref = "markdownVer"}

# Required
purchases-core = { module = "com.revenuecat.purchases:purchases-kmp-core", version.ref = "purchases-kmp" }
# Optional: adds extension properties representing timestamps as kotlinx-datetime Instants.
purchases-datetime = { module = "com.revenuecat.purchases:purchases-kmp-datetime", version.ref = "purchases-kmp" }
# Optional: adds suspending functions that return Arrow's Either to indicate success / failure.
purchases-either = { module = "com.revenuecat.purchases:purchases-kmp-either", version.ref = "purchases-kmp" }
# Optional: adds suspending functions that return kotlin.Result to indicate success / failure.
purchases-result = { module = "com.revenuecat.purchases:purchases-kmp-result", version.ref = "purchases-kmp" }

multiplatform-settings = { module = "com.russhwolf:multiplatform-settings", version.ref = "settingsVer" }
multiplatform-settings-no-arg = { module = "com.russhwolf:multiplatform-settings-no-arg", version.ref = "settingsVer" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agpVer" }
android-library = { id = "com.android.library", version.ref = "agpVer" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlinVer" }
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlinVer" }
kotlin-plugin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlinVer" }
kotlin-compose = { id = "org.jetbrains.compose", version.ref = "kotlinComposeVer" }
#kotlin-cocoapods = { id = "org.jetbrains.kotlin.native.cocoapods", version.ref = "kotlinVer" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlinVer" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlinVer" }
google-services = { id = "com.google.gms.google-services", version.ref = "google-services" }